version: '3.8'

services:
  # Backend API
  atm-backend:
    build: 
      context: ./atm-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./atm-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    networks:
      - atm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Web
  atm-frontend:
    build:
      context: ./atm-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./atm-frontend:/usr/share/nginx/html:ro
    depends_on:
      - atm-backend
    networks:
      - atm-network
    restart: unless-stopped
    environment:
      - API_URL=http://atm-backend:3000

  # Nginx Proxy (Opcional - para produção)
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - atm-frontend
      - atm-backend
    networks:
      - atm-network
    restart: unless-stopped

networks:
  atm-network:
    driver: bridge

volumes:
  atm-data:
    driver: local